/*
 * agent/service.proto
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: version not set
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import org.openapitools.client.model.AgentUpdatePayload;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for AgentUpdateAgentRequest
 */
public class AgentUpdateAgentRequestTest {
    private final AgentUpdateAgentRequest model = new AgentUpdateAgentRequest();

    /**
     * Model tests for AgentUpdateAgentRequest
     */
    @Test
    public void testAgentUpdateAgentRequest() {
        // TODO: test AgentUpdateAgentRequest
    }

    /**
     * Test the property 'payload'
     */
    @Test
    public void payloadTest() {
        // TODO: test payload
    }

    /**
     * Test the property 'payloadMask'
     */
    @Test
    public void payloadMaskTest() {
        // TODO: test payloadMask
    }

}
