/*
 * agent/service.proto
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: version not set
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.openapitools.client.model.ListRequestFilters;
import org.openapitools.client.model.ListRequestSort;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for AgentListAgentsRequest
 */
public class AgentListAgentsRequestTest {
    private final AgentListAgentsRequest model = new AgentListAgentsRequest();

    /**
     * Model tests for AgentListAgentsRequest
     */
    @Test
    public void testAgentListAgentsRequest() {
        // TODO: test AgentListAgentsRequest
    }

    /**
     * Test the property 'pageToken'
     */
    @Test
    public void pageTokenTest() {
        // TODO: test pageToken
    }

    /**
     * Test the property 'sorts'
     */
    @Test
    public void sortsTest() {
        // TODO: test sorts
    }

    /**
     * Test the property 'filtersMask'
     */
    @Test
    public void filtersMaskTest() {
        // TODO: test filtersMask
    }

    /**
     * Test the property 'filters'
     */
    @Test
    public void filtersTest() {
        // TODO: test filters
    }

}
