/*
 * agent/service.proto
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: version not set
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.api;

import GeminiCommerce_Agent.ApiException;
import org.openapitools.client.model.AgentAgentEntity;
import org.openapitools.client.model.AgentCreateAgentRequest;
import org.openapitools.client.model.AgentListAgentsRequest;
import org.openapitools.client.model.AgentListResponse;
import org.openapitools.client.model.AgentUpdateAgentRequest;
import org.openapitools.client.model.RpcStatus;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for AgentApi
 */
@Disabled
public class AgentApiTest {

    private final AgentApi api = new AgentApi();

    /**
     * @throws ApiException if the Api call fails
     */
    @Test
    public void agentCreateAgentTest() throws ApiException {
        String tenantId = null;
        AgentCreateAgentRequest body = null;
        AgentAgentEntity response = api.agentCreateAgent(tenantId, body);
        // TODO: test validations
    }

    /**
     * @throws ApiException if the Api call fails
     */
    @Test
    public void agentGetAgentTest() throws ApiException {
        String tenantId = null;
        String id = null;
        AgentAgentEntity response = api.agentGetAgent(tenantId, id);
        // TODO: test validations
    }

    /**
     * @throws ApiException if the Api call fails
     */
    @Test
    public void agentListAgentsTest() throws ApiException {
        String tenantId = null;
        Long pageSize = null;
        AgentListAgentsRequest body = null;
        AgentListResponse response = api.agentListAgents(tenantId, pageSize, body);
        // TODO: test validations
    }

    /**
     * @throws ApiException if the Api call fails
     */
    @Test
    public void agentUpdateAgentTest() throws ApiException {
        String tenantId = null;
        String id = null;
        AgentUpdateAgentRequest body = null;
        AgentAgentEntity response = api.agentUpdateAgent(tenantId, id, body);
        // TODO: test validations
    }

}
